gui:
  theme:
    activeBorderColor:
      - green
      - bold
  showIcons: false
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
      useConfig: true
  commit:
    signOff: false
keybinding:
  universal:
    quit: 'q'
    return: '<esc>'
