require("squirrel.lazy")
require("squirrel.mason")
require("squirrel.remap")
require("squirrel.set")
require("squirrel.utilities")
-- require 'squirrel.lsp'
require("squirrel.lspnew")
require("squirrel.treesitter")
require("squirrel.dap")
require("squirrel.dapui")
require("squirrel.whichkey")
require("squirrel.telescope")
require("squirrel.luasnip")
require("squirrel.blink-cmp")
-- require 'squirrel.cmp'
require("squirrel.oil")
require("squirrel.undotree")
require("squirrel.gitsigns")
require("squirrel.colors")
require("squirrel.notify")
require("squirrel.noice")
--require 'squirrel.trouble'
require("squirrel.dotnet")
-- require 'squirrel.obsidian'
require("squirrel.commands")
